# .NET CI Workflow
name: .NET CI
# Run on several operating systems
on: [push, pull_request]

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Find test projects
      run: echo "testprojects=$(find ./dotnet -type f -name "*Tests.csproj" ! -path "*IntegrationTests*" | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Run tests
      run: dotnet test ${{ env.testprojects }} --no-restore --verbosity normal

  build-and-test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Find test projects
      run: echo "testprojects=$(find ./dotnet -type f -name "*Tests.csproj" | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Run tests
      run: dotnet test ${{ env.testprojects }} --no-restore --verbosity normal

  build-and-test-macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Find test projects
      run: echo "testprojects=$(find ./dotnet -type f -name "*Tests.csproj" | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Run tests
      run: dotnet test ${{ env.testprojects }} --no-restore --verbosity normal
